version: '3.9'

services:
  postgres:
    build: ./postgres
    restart: unless-stopped
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  spotlas:
    build:
      context: ./endpoint
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: on-failure
